name: process_order_service
version: 1.0.2
kafka_trigger: 
  topic: orders
  batch_size: 1
  consumer_group_id: 551C6134-0B07-416C-95BF-77442C28F877
db:
  endpoint: order-processing-rds.cu13msmnkxn8.us-east-1.rds.amazonaws.com
  port: 5432
  name: customer_orders
  username: dev
  password: aws/secretsmanager/db/customer_orders/password20230924183723841600000001
kafka:
  endpoint: b-1.ordersprocesskafkaclu.o23kam.c10.kafka.us-east-1.amazonaws.com:9094,b-2.ordersprocesskafkaclu.o23kam.c10.kafka.us-east-1.amazonaws.com:9094
  topic: products
